# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ["--maxkb=50000"] # github warning limit
    - id: check-toml
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --strict]
- repo: https://github.com/PyCQA/flake8
  rev: "7.2.0"
  hooks:
  - id: flake8
    # max-line-length setting is the same as black
    args: [--max-line-length, "150", --ignore=E402,--ignore=E800]
    additional_dependencies: [flake8-bugbear, flake8-builtins, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity,flake8-docstrings]
- repo: https://github.com/pylint-dev/pylint
  rev: v3.3.7
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      types: [python]
      additional_dependencies: []
      # ignore pymupdf which do not have type hints
      args: [--max-line-length,"150"]

# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.13.0
#   hooks:
#     - id: markdownlint
#       # ignore line length of makrdownlint
#       args: [-r, ~MD013]
