name: Bug Report
description: Report a reproducible bug in the application
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us reproduce and fix the issue.
  - type: input
    id: title
    attributes:
      label: Bug Summary
      placeholder: Short and descriptive summary of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run `python example.py`
        2. Observe the error
      description: Please provide a minimal, reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Error Traceback or Logs (if applicable)
      render: shell
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "e.g., Ubuntu 20.04, Python 3.10"
    validations:
      required: false
