name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! Please complete the form below.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: e.g., Add support for JSON output
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe how you'd like the feature to work
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered?
    validations:
      required: false
