name: Question
description: Ask a question related to usage or development
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question, please provide sufficient context so we can assist you better.
  - type: input
    id: summary
    attributes:
      label: Question Summary
      placeholder: e.g., How to run the simulation with custom input?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context or Background
      description: What are you trying to do? Any relevant files or errors?
    validations:
      required: false
